# Generated by Django 3.2.8 on 2021-10-21 13:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Clan', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('time_active', models.CharField(max_length=32)),
                ('alias_one', models.CharField(max_length=32)),
                ('alias_two', models.CharField(max_length=32)),
                ('alias_three', models.CharField(max_length=32)),
                ('alias_four', models.CharField(max_length=32)),
                ('clan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clan', to='Clan.clan')),
                ('clan_leader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clan_leader', to='Clan.clan')),
            ],
        ),
    ]
