# Generated by Django 3.2.8 on 2021-10-21 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Player', '0002_alter_player_clan_leader'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='clan_leader',
        ),
    ]
