# Generated by Django 3.2.8 on 2021-10-21 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Player', '0004_alter_player_clan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='clan',
        ),
    ]
