# Generated by Django 3.2.8 on 2021-10-21 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Player', '0005_remove_player_clan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='alias_four',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='alias_one',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='alias_three',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='alias_two',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
