# Generated by Django 3.2.8 on 2021-10-21 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Player', '0006_auto_20211021_0818'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='bio',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
